// Continent and region data (removed global icons)
export const CONTINENTS = [
  { value: 'Global', label: 'Global', description: 'Worldwide search' },
  {
    value: 'North America',
    label: 'North America',
    description: 'US, Canada, Mexico',
  },
  { value: 'Europe', label: 'Europe', description: 'European Union & UK' },
  {
    value: 'Asia Pacific',
    label: 'Asia Pacific',
    description: 'Asia & Oceania',
  },
  {
    value: 'Latin America',
    label: 'Latin America',
    description: 'South & Central America',
  },
  { value: 'Africa', label: 'Africa', description: 'African countries' },
  {
    value: 'Middle East',
    label: 'Middle East',
    description: 'Middle Eastern countries',
  },
];

export const COUNTRIES_BY_REGION = {
  'North America': [
    { value: 'United States', label: 'United States' },
    { value: 'Canada', label: 'Canada' },
    { value: 'Mexico', label: 'Mexico' },
  ],
  Europe: [
    { value: 'United Kingdom', label: 'United Kingdom' },
    { value: 'Germany', label: 'Germany' },
    { value: 'France', label: 'France' },
    { value: 'Spain', label: 'Spain' },
    { value: 'Italy', label: 'Italy' },
    { value: 'Netherlands', label: 'Netherlands' },
    { value: 'Belgium', label: 'Belgium' },
    { value: 'Switzerland', label: 'Switzerland' },
    { value: 'Austria', label: 'Austria' },
    { value: 'Sweden', label: 'Sweden' },
    { value: 'Norway', label: 'Norway' },
    { value: 'Denmark', label: 'Denmark' },
    { value: 'Finland', label: 'Finland' },
    { value: 'Poland', label: 'Poland' },
    { value: 'Czech Republic', label: 'Czech Republic' },
    { value: 'Hungary', label: 'Hungary' },
    { value: 'Romania', label: 'Romania' },
    { value: 'Bulgaria', label: 'Bulgaria' },
    { value: 'Greece', label: 'Greece' },
    { value: 'Portugal', label: 'Portugal' },
    { value: 'Ireland', label: 'Ireland' },
    { value: 'Iceland', label: 'Iceland' },
    { value: 'Luxembourg', label: 'Luxembourg' },
    { value: 'Slovakia', label: 'Slovakia' },
    { value: 'Slovenia', label: 'Slovenia' },
    { value: 'Croatia', label: 'Croatia' },
    { value: 'Estonia', label: 'Estonia' },
    { value: 'Latvia', label: 'Latvia' },
    { value: 'Lithuania', label: 'Lithuania' },
  ],
  'Asia Pacific': [
    { value: 'Japan', label: 'Japan' },
    { value: 'South Korea', label: 'South Korea' },
    { value: 'China', label: 'China' },
    { value: 'India', label: 'India' },
    { value: 'Australia', label: 'Australia' },
    { value: 'New Zealand', label: 'New Zealand' },
    { value: 'Singapore', label: 'Singapore' },
    { value: 'Malaysia', label: 'Malaysia' },
    { value: 'Thailand', label: 'Thailand' },
    { value: 'Vietnam', label: 'Vietnam' },
    { value: 'Philippines', label: 'Philippines' },
    { value: 'Indonesia', label: 'Indonesia' },
    { value: 'Taiwan', label: 'Taiwan' },
    { value: 'Hong Kong', label: 'Hong Kong' },
    { value: 'Pakistan', label: 'Pakistan' },
    { value: 'Bangladesh', label: 'Bangladesh' },
    { value: 'Sri Lanka', label: 'Sri Lanka' },
    { value: 'Nepal', label: 'Nepal' },
    { value: 'Myanmar', label: 'Myanmar' },
    { value: 'Cambodia', label: 'Cambodia' },
    { value: 'Laos', label: 'Laos' },
    { value: 'Mongolia', label: 'Mongolia' },
    { value: 'Kazakhstan', label: 'Kazakhstan' },
    { value: 'Uzbekistan', label: 'Uzbekistan' },
    { value: 'Kyrgyzstan', label: 'Kyrgyzstan' },
    { value: 'Tajikistan', label: 'Tajikistan' },
    { value: 'Turkmenistan', label: 'Turkmenistan' },
  ],
  'Latin America': [
    { value: 'Brazil', label: 'Brazil' },
    { value: 'Argentina', label: 'Argentina' },
    { value: 'Chile', label: 'Chile' },
    { value: 'Colombia', label: 'Colombia' },
    { value: 'Peru', label: 'Peru' },
    { value: 'Venezuela', label: 'Venezuela' },
    { value: 'Ecuador', label: 'Ecuador' },
    { value: 'Bolivia', label: 'Bolivia' },
    { value: 'Paraguay', label: 'Paraguay' },
    { value: 'Uruguay', label: 'Uruguay' },
    { value: 'Guyana', label: 'Guyana' },
    { value: 'Suriname', label: 'Suriname' },
    { value: 'Costa Rica', label: 'Costa Rica' },
    { value: 'Panama', label: 'Panama' },
    { value: 'Nicaragua', label: 'Nicaragua' },
    { value: 'Honduras', label: 'Honduras' },
    { value: 'El Salvador', label: 'El Salvador' },
    { value: 'Guatemala', label: 'Guatemala' },
    { value: 'Belize', label: 'Belize' },
    { value: 'Cuba', label: 'Cuba' },
    { value: 'Jamaica', label: 'Jamaica' },
    { value: 'Haiti', label: 'Haiti' },
    { value: 'Dominican Republic', label: 'Dominican Republic' },
    { value: 'Puerto Rico', label: 'Puerto Rico' },
  ],
  Africa: [
    { value: 'South Africa', label: 'South Africa' },
    { value: 'Nigeria', label: 'Nigeria' },
    { value: 'Egypt', label: 'Egypt' },
    { value: 'Kenya', label: 'Kenya' },
    { value: 'Ethiopia', label: 'Ethiopia' },
    { value: 'Ghana', label: 'Ghana' },
    { value: 'Morocco', label: 'Morocco' },
    { value: 'Tanzania', label: 'Tanzania' },
    { value: 'Uganda', label: 'Uganda' },
    { value: 'Algeria', label: 'Algeria' },
    { value: 'Sudan', label: 'Sudan' },
    { value: 'Angola', label: 'Angola' },
    { value: 'Mozambique', label: 'Mozambique' },
    { value: 'Zimbabwe', label: 'Zimbabwe' },
    { value: 'Zambia', label: 'Zambia' },
    { value: 'Malawi', label: 'Malawi' },
    { value: 'Botswana', label: 'Botswana' },
    { value: 'Namibia', label: 'Namibia' },
    { value: 'Lesotho', label: 'Lesotho' },
    { value: 'Eswatini', label: 'Eswatini' },
    { value: 'Madagascar', label: 'Madagascar' },
    { value: 'Mauritius', label: 'Mauritius' },
    { value: 'Seychelles', label: 'Seychelles' },
    { value: 'Comoros', label: 'Comoros' },
    { value: 'Cape Verde', label: 'Cape Verde' },
    { value: 'São Tomé and Príncipe', label: 'São Tomé and Príncipe' },
    { value: 'Equatorial Guinea', label: 'Equatorial Guinea' },
    { value: 'Gabon', label: 'Gabon' },
    { value: 'Congo', label: 'Congo' },
    { value: 'Central African Republic', label: 'Central African Republic' },
    { value: 'Cameroon', label: 'Cameroon' },
    { value: 'Chad', label: 'Chad' },
    { value: 'Niger', label: 'Niger' },
    { value: 'Mali', label: 'Mali' },
    { value: 'Burkina Faso', label: 'Burkina Faso' },
    { value: 'Senegal', label: 'Senegal' },
    { value: 'Gambia', label: 'Gambia' },
    { value: 'Guinea-Bissau', label: 'Guinea-Bissau' },
    { value: 'Guinea', label: 'Guinea' },
    { value: 'Sierra Leone', label: 'Sierra Leone' },
    { value: 'Liberia', label: 'Liberia' },
    { value: 'Ivory Coast', label: 'Ivory Coast' },
    { value: 'Togo', label: 'Togo' },
    { value: 'Benin', label: 'Benin' },
    { value: 'Rwanda', label: 'Rwanda' },
    { value: 'Burundi', label: 'Burundi' },
    { value: 'Somalia', label: 'Somalia' },
    { value: 'Djibouti', label: 'Djibouti' },
    { value: 'Eritrea', label: 'Eritrea' },
    { value: 'Libya', label: 'Libya' },
    { value: 'Tunisia', label: 'Tunisia' },
    { value: 'Western Sahara', label: 'Western Sahara' },
  ],
  'Middle East': [
    { value: 'Saudi Arabia', label: 'Saudi Arabia' },
    { value: 'Iran', label: 'Iran' },
    { value: 'Iraq', label: 'Iraq' },
    { value: 'Turkey', label: 'Turkey' },
    { value: 'Israel', label: 'Israel' },
    { value: 'Lebanon', label: 'Lebanon' },
    { value: 'Syria', label: 'Syria' },
    { value: 'Jordan', label: 'Jordan' },
    { value: 'Kuwait', label: 'Kuwait' },
    { value: 'Qatar', label: 'Qatar' },
    { value: 'United Arab Emirates', label: 'United Arab Emirates' },
    { value: 'Oman', label: 'Oman' },
    { value: 'Yemen', label: 'Yemen' },
    { value: 'Bahrain', label: 'Bahrain' },
    { value: 'Cyprus', label: 'Cyprus' },
    { value: 'Palestine', label: 'Palestine' },
    { value: 'Azerbaijan', label: 'Azerbaijan' },
    { value: 'Georgia', label: 'Georgia' },
    { value: 'Armenia', label: 'Armenia' },
  ],
};
